[package]
name = "rust-tracing"
version = "0.1.0"
edition = "2021"


[dependencies]
indicatif = "0.17.7"
pixels = "0.13.0"
rand = "0.8.5"
rayon = "1.8.0"
fltk = { version = "1", features = ["rwh05", "no-images", "no-pango"] }
clap = { version = "4.4.8", features = ["derive"] }
image = "0.24.7"
